package modelo.entidad;
// Generated 04-dic-2018 22:25:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modelo generated by hbm2java
 */
public class Modelo  implements java.io.Serializable {


     private Integer idmodelo;
     private Marca marca;
     private String nombre;
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public Modelo() {
    }

	
    public Modelo(Marca marca, String nombre) {
        this.marca = marca;
        this.nombre = nombre;
    }
    public Modelo(Marca marca, String nombre, Set<Stock> stocks) {
       this.marca = marca;
       this.nombre = nombre;
       this.stocks = stocks;
    }
   
    public Integer getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(Integer idmodelo) {
        this.idmodelo = idmodelo;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


