package modelo.entidad;
// Generated 04-dic-2018 22:25:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer idmovil;
     private Marca marca;
     private Modelo modelo;
     private BigDecimal costo;
     private BigDecimal precioVenta;
     private Date DIngreso;
     private int cantidad;
     private boolean estado;
     private Set<Movimientos> movimientoses = new HashSet<Movimientos>(0);

    public Stock() {
    }

	
    public Stock(Marca marca, Modelo modelo, BigDecimal costo, BigDecimal precioVenta, Date DIngreso, int cantidad, boolean estado) {
        this.marca = marca;
        this.modelo = modelo;
        this.costo = costo;
        this.precioVenta = precioVenta;
        this.DIngreso = DIngreso;
        this.cantidad = cantidad;
        this.estado = estado;
    }
    public Stock(Marca marca, Modelo modelo, BigDecimal costo, BigDecimal precioVenta, Date DIngreso, int cantidad, boolean estado, Set<Movimientos> movimientoses) {
       this.marca = marca;
       this.modelo = modelo;
       this.costo = costo;
       this.precioVenta = precioVenta;
       this.DIngreso = DIngreso;
       this.cantidad = cantidad;
       this.estado = estado;
       this.movimientoses = movimientoses;
    }
   
    public Integer getIdmovil() {
        return this.idmovil;
    }
    
    public void setIdmovil(Integer idmovil) {
        this.idmovil = idmovil;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Date getDIngreso() {
        return this.DIngreso;
    }
    
    public void setDIngreso(Date DIngreso) {
        this.DIngreso = DIngreso;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Movimientos> getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set<Movimientos> movimientoses) {
        this.movimientoses = movimientoses;
    }




}


