package modelo.entidad;
// Generated 04-dic-2018 22:25:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private String nombre;
     private String apellido;
     private String user;
     private String password;
     private Date fechaIngreso;
     private Set<Movimientos> movimientoses = new HashSet<Movimientos>(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String apellido, String user, String password, Date fechaIngreso) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.user = user;
        this.password = password;
        this.fechaIngreso = fechaIngreso;
    }
    public Usuario(String nombre, String apellido, String user, String password, Date fechaIngreso, Set<Movimientos> movimientoses) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.user = user;
       this.password = password;
       this.fechaIngreso = fechaIngreso;
       this.movimientoses = movimientoses;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Set<Movimientos> getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set<Movimientos> movimientoses) {
        this.movimientoses = movimientoses;
    }




}


